[package]
name = "kvdb"
version = "0.1.0"
authors = ["June Yi <jytechdevops@gmail.com>"]
description = "A key-value store"
edition = "2021"

[lib]
name = "kvdb"

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"